language: c 

sudo: required

services:
 - docker

env:
  matrix:
    - DISTRO=fedora SYSTEM_LIBS=OFF
    - DISTRO=fedora SYSTEM_LIBS=ON DOCKERHUB=true
    - DISTRO=ubuntu SYSTEM_LIBS=OFF
    - DISTRO=ubuntu SYSTEM_LIBS=ON DOCKERHUB=true
    - DISTRO=fedora_mpich SYSTEM_LIBS=OFF
    - DISTRO=fedora_mpich SYSTEM_LIBS=ON DOCKERHUB=true
    - DISTRO=ubuntu_mpich SYSTEM_LIBS=OFF
    - DISTRO=ubuntu_mpich SYSTEM_LIBS=ON DOCKERHUB=true
    - DISTRO=fedora SYSTEM_LIBS=OFF CMAKE_BUILD_TYPE=Debug
    - DISTRO=ubuntu SYSTEM_LIBS=OFF CMAKE_BUILD_TYPE=Debug
    - DISTRO=fedora_mpich SYSTEM_LIBS=ON CMAKE_BUILD_TYPE=Debug
    - DISTRO=ubuntu_mpich SYSTEM_LIBS=ON CMAKE_BUILD_TYPE=Debug
    
before_install:
  - df -h
  - du -sh *
  - git submodule update --init --recursive --recommend-shallow
 
script:
  - cp -vr docker ${HOME}/docker
  - sed -i "1s/fedora/${DISTRO}/" ${HOME}/docker/Dockerfile
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - ccache -z
  - cp -r ${HOME}/.ccache ${HOME}/docker/ccache
  - if [[ ${CMAKE_BUILD_TYPE} ]]; then TAG="_${CMAKE_BUILD_TYPE}"; fi
  - if [[ ${TRAVIS_BRANCH} != master ]]; then TAG="${TAG}_${TRAVIS_BRANCH//[^a-zA-Z0-9]/_}"; fi
  - docker build --build-arg SYSTEM_LIBS=${SYSTEM_LIBS}
                 --build-arg CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
                 --build-arg CI=${CI} --build-arg TRAVIS=${TRAVIS}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                 -t ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} ${HOME}/docker/ &&
    rm -rf ${HOME}/.ccache &&
    CON=$(docker run -d ${TRAVIS_REPO_SLUG}:${DISTRO}${TAG} /bin/bash) &&
    docker cp ${CON}:/home/flecsi/.ccache ${HOME}/
  - ccache -s

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master|refactor) ]] && DEPLOY=yes
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:${DISTRO}${TAG}";
   fi

cache:
  - ccache
  
git:
  submodules: false
